# Generated by Django 5.2.8 on 2025-11-16 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('named_url', models.CharField(blank=True, max_length=100, verbose_name='named URL')),
                ('explicit_url', models.CharField(blank=True, max_length=200, verbose_name='explicit URL')),
                ('menu_name', models.CharField(max_length=50, verbose_name='menu name')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_app.menuitem', verbose_name='parent menu item')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ['menu_name', 'order', 'name'],
            },
        ),
    ]
